[versions]
kotlin = "1.7.22"
coroutines = "1.6.4"
ktor = "2.1.3"

[libraries]
graphql = { module = "com.graphql-java:graphql-java", version = "19.3" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.1" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
formatting = { module = "com.facebook:ktfmt", version = "0.39" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }

logging-logback = { module = "ch.qos.logback:logback-classic", version = "1.2.11" }